openapi: 3.0.0
info: 
  description: This API provides event stats 
  version: "1.0.0" 
  title: Stats API 
  contact: 
    email: hmurtaza@my.bcit.ca

paths: 
  /health: 
    get: 
      summary: Gets the health 
      operationId: app.get_health 
      description: Gets health of other services
      responses: 
        '200': 
          description: Successfully returned a list of health checks
          content: 
            application/json: 
              schema: 
                type: object 
                properties: 
                  message: 
                    type: string
        '400': 
          description: Invalid request 
          content: 
            application/json: 
              schema: 
                type: object 
                properties: 
                  message: 
                    type: string
